---

- name: download filebeat
  when: not filebeat_store_name is exists
  delegate_to: localhost
  get_url:
    url: "{{ filebeat_download_url }}"
    validate_certs: no
    dest: "{{ soft_dir }}"

- name: scp soft
  synchronize:
    src: "{{ filebeat_store_name }}"
    dest: "{{ soft_dir }}"
    mode: push

- name: unarchive soft
  unarchive:
    src: "{{ filebeat_store_name }}"
    dest: "{{ filebeat_install_dir }}"

- name: link dir filebeat
  file:
    state: link
    path: "{{ filebeat_install_name }}"
    src: "{{ filebeat_install_name }}"
    dest: "{{ filebeat_link_dir }}"
    force: yes
    follow: yes
