---
# defaults file for zabbix_server
zabbix_version: zabbix-4.0.11
zabbix_download_url: https://nchc.dl.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/4.0.11/zabbix-4.0.11.tar.gz
soft_dir: /root/softs/
zabbix_install_dir: /usr/local/zabbix/
zabbix_store_name: "{{ soft_dir }}/{{ zabbix_version }}.tar.gz"
user: zabbix
group: zabbix
config_cmd: "./configure --prefix={{ zabbix_install_dir }} --enable-server --enable-agent --with-mysql --with-net-snmp --with-libcurl --with-libxml2 --enable-proxy --enable-java --enable-ipv6 && make && make install"
php_dir: "/www/web/zabbix"
