---

- hosts: codis
  remote_user: root
  # pre_tasks:
  #  - name: test go
  #    shell: ". /etc/profile && go version | awk '{print $3}' |cut -b 3-"
  #    register: go_version
  #    ignore_errors: yes
   
  #  - debug: msg="{{ go_version }}"
  roles:
    - role: linux_jdk1.8
    - role: supervisor
    - role: zookeeper_cluster
    - role: etcd_source_cluster
    - role: golang_linux
 #     when: go_version.rc != 0
    - role: codis_cluster
