---

- name: create softswares dir and install dir
  file: "path={{ item }} state=directory"
  with_items:
    - "{{ SOFT_DIR }}"
    - "{{ INSTALL_DIR }}"
    - "{{ ETCD_DIR }}"
    - "{{ ETCD_CONF_DIR }}"

- name: download software file
  get_url:
    url: "{{ download_url }}"
    validate_certs: no
    dest: /root/softs/
  delegate_to: localhost
  when: not etcd_store_name is exists

- name: scp software file
  synchronize: "src={{ etcd_store_name }} dest={{ SOFT_DIR }} mode=push"

#- name: register file
#  shell: "ls {{ INSTALL_DIR }} | wc -l"
#  register: exist_install_dir
#  check_mode: no
#
#- debug: msg="{{ exist_install_dir }}"

- name: unarchive software file
  unarchive: "src={{ etcd_store_name }} dest={{ INSTALL_DIR }} copy=no"

- name: link etcd dir
  file: "path={{ ETCD_INSTALL_DIR }} state=link src={{ ETCD_INSTALL_DIR }} dest={{ etcd_link_dir }} follow=yes force=yes"
