---
# defaults file for filebeat
soft_dir: /root/softs/
filebeat_version: filebeat-6.4.0
filebeat_download_url: "https://artifacts.elastic.co/downloads/beats/filebeat/{{ filebeat_version }}-linux-x86_64.tar.gz"
filebeat_store_name: "{{ soft_dir }}/{{ filebeat_version }}-linux-x86_64.tar.gz" 
filebeat_install_dir: /usr/local/
filebeat_install_name: "{{ filebeat_install_dir }}{{ filebeat_version }}-linux-x86_64"
filebeat_link_dir: "{{ filebeat_install_dir }}/filebeat"
filebeat_log_dir: "{{ filebeat_link_dir }}/logs/"
filebeat_rule_conf_dir: "{{ filebeat_link_dir }}/rules.d"
filebeat_node_conf_dir: "{{ filebeat_link_dir }}/conf.d"
filebeat_main_conf: "{{ filebeat_link_dir }}/filebeat.yml"
filebeat_bin: "{{ filebeat_link_dir }}/filebeat"
filebeat_start_cmd: "{{ filebeat_bin }} -e -c {{ filebeat_main_conf }} -d publish"
supervisor_redhat_dir: /etc/supervisord.d/
supervisor_debian_dir: /etc/supervisor/conf.d/
es_url: "{{ ansible_ssh_host }}:9200"
kibana_url: "{{ ansible_ssh_host }}:5601"

