---

- name: config kibana config
  template: 
    src: kibana.yml.j2
    dest: "{{ kibana_main_conf }}"

- name: config tengine kibana conf
  template:
    src: kibana.conf.j2
    dest: "{{ tengine_vhost_dir }}/kibana.conf"

- name: add kibana to supervisor for redhat
  template:
    src: kibana.ini.j2
    dest: "{{ supervisor_redhat_dir }}/kibana.ini"
  notify:
    reread_and_update_supervisor_redhat
  when: ansible_os_family == 'RedHat'

- name: add kibana to supervisor for debian
  template:
    src: kibana.ini.j2
    dest: "{{ supervisor_debian_dir }}/kibana.ini"
  notify:
    reread_and_update_supervisor_debian
  when: ansible_os_family == 'Debian'
