---

- name: download kibana
  when: not kibana_store_name is exists
  delegate_to: localhost
  get_url:
    url: "{{ kibana_download_url }}"
    validate_certs: no
    dest: "{{ soft_dir }}"

- name: scp soft
  synchronize:
    src: "{{ kibana_store_name }}"
    dest: "{{ soft_dir }}"
    mode: push

- name: unarchive soft
  unarchive:
    src: "{{ kibana_store_name }}"
    dest: "{{ kibana_install_dir }}"

- name: link dir kibana
  file:
    state: link
    path: "{{ kibana_install_name }}"
    src: "{{ kibana_install_name }}"
    dest: "{{ kibana_link_dir }}"
    force: yes
    follow: yes
