---

- name: create nsqadmin  config
  template: "src=nsqadmin.cfg.j2 dest={{ nsq_conf_dir }}/nsqadmin.cfg"

- name: create nsqd  config
  template: "src=nsqd.cfg.j2 dest={{ nsq_conf_dir }}/nsqd.cfg"

- name: create nsqlookupd  config
  template: "src=nsqlookupd.cfg.j2 dest={{ nsq_conf_dir }}/nsqlookupd.cfg"

- name: create supervisor_nsqadmin  config for redhat
  template: "src=nsqadmin.ini.j2 dest={{ supervisor_redhat_dir }}/nsqadmin.ini"
  when: ansible_os_family == 'RedHat'

- name: create supervisor_nsqadmin  config for debian
  template: "src=nsqadmin.ini.j2 dest={{ supervisor_debian_dir }}/nsqadmin.conf"
  when: ansible_os_family == 'Debian'

- name: create supervisor_nsqd  config for redhat
  template: "src=nsqd.ini.j2 dest={{ supervisor_redhat_dir }}/nsqd.ini"
  when: ansible_os_family == 'RedHat'

- name: create supervisor_nsqadmin  config for debian
  template: "src=nsqd.ini.j2 dest={{ supervisor_debian_dir }}/nsqd.conf"
  when: ansible_os_family == 'Debian'

- name: create supervisor_nsqlookupd  config for redhat
  template: "src=nsqlookupd.ini.j2 dest={{ supervisor_redhat_dir }}/nsqlookupd.ini"
  when: ansible_os_family == 'RedHat'

- name: create supervisor_nsqadmin  config for debian
  template: "src=nsqlookupd.ini.j2 dest={{ supervisor_debian_dir }}/nsqlookupd.conf"
  when: ansible_os_family == 'Debian'
