---

- name: donwload youzan nsq ha 
  get_url:
    url: "{{ nsq_ha_download_url }}"
    dest: "{{ soft_dir }}"
    validate_certs: no
  delegate_to: localhost
  when: not nsq_store_name is exists

- name: copy soft
  synchronize: "src={{ nsq_store_name }} dest={{ soft_dir }} mode=push"

- name: unarchive nsq soft and install
  unarchive: "src={{ nsq_store_name }} dest={{ nsq_install_dir }} copy=yes creates={{ nsq_dir }}"

- name: create nsq dir
  file: "path={{ item }} state=directory"
  with_items:
    - "{{ nsq_data_path }}"
    - "{{ nsqd_log_dir }}"
    - "{{ nsqlookupd_log_dir }}"
    - "{{ nsqadmin_log_dir }}"
    - "{{ soft_dir  }}"
    - "{{ nsq_conf_dir }}"
