---
# defaults file for kibana
soft_dir: /root/softs/
kibana_version: kibana-6.4.0
kibana_download_url: "https://artifacts.elastic.co/downloads/kibana/{{ kibana_version }}-linux-x86_64.tar.gz"
kibana_store_name: "{{ soft_dir }}/{{ kibana_version }}-linux-x86_64.tar.gz" 
kibana_install_dir: /usr/local
kibana_install_name: "{{ kibana_install_dir }}/{{ kibana_version }}-linux-x86_64"
kibana_link_dir: "{{ kibana_install_dir }}/kibana"
kibana_conf_dir: "{{ kibana_link_dir }}/config/"
kibana_main_conf: "{{ kibana_conf_dir }}/kibana.yml"
kibana_bin: "{{ kibana_link_dir }}/bin/kibana"
kibana_start_cmd: "{{ kibana_bin }}"
kibana_es_url: "http://{{ ansible_ssh_host }}:9200"
kibana_host: "{{ ansible_ssh_host }}"
kibana_port: 5601
kibana_http_domain: kibana.yikaobang.com.cn
tengine_vhost_dir: /usr/local/tengine/conf/vhost/
nginx_bin: /usr/local/tengine/sbin/nginx
supervisor_redhat_dir: /etc/supervisord.d/
supervisor_debian_dir: /etc/supervisor/conf.d/
