---

- name: config mongo config conf 21004
  template: "src=mongo_config.conf.j2 dest={{ mongo_config_conf }}"

- name: config shard1 config conf 21001
  template: "src=shard1.conf.j2 dest={{ shard1_config }}"

- name: config shard2 config conf 21002
  template: "src=shard2.conf.j2 dest={{ shard2_config }}"

- name: config shard3 config conf 21003
  template: "src=shard3.conf.j2 dest={{ shard3_config }}"

- name: config mongos config conf 21000
  template: "src=mongos.conf.j2 dest={{ mongos_config }}"


