---

- name: create user and group
  group: "name={{ group }}"

- name: create user and user
  user: "name={{ user }} group={{ group }}"

- name: create need dir
  file: "path={{ item }} state=directory group={{ group }} owner={{ user }}"
  with_items:
    - "{{ mongo_data_dir }}"
    - "{{ mongo_config_dir }}"
    - "{{ mongo_config_log_dir }}"
    - "{{ mongo_config_data_dir }}"
    - "{{ shard1_data_dir }}"
    - "{{ shard1_log_dir }}"
    - "{{ shard2_data_dir }}"
    - "{{ shard2_log_dir }}"
    - "{{ shard3_data_dir }}"
    - "{{ shard3_log_dir }}"
    - "{{ mongos_log_dir }}"
    - "{{ shard3_log_dir }}"

- name: download mongodb soft
  get_url: 
    url: "{{ mongodb_download_url }}"
    dest: "{{ soft_dir }}"
    validate_certs: no
  delegate_to: localhost
  when: not soft_store_name is exists

- name: scp mongodb soft
  synchronize: "src={{ soft_store_name }} dest={{ soft_dir }} mode=push"

- name: unarchive mongodb soft
  unarchive: "src={{ soft_store_name }} dest={{ install_dir }} copy=no creates={{ install_dir_name }}"

- name: create link dir
  file: "path={{ install_dir_name }} src={{ install_dir_name }} dest={{ install_link_dir }} state=link group={{ group }} owner={{ user }}"
