---
# handlers file for kibana

- name: reread_and_update_supervisor_redhat
  supervisorctl:
    state: present
    name: kibana
    config: "{{ supervisor_redhat_dir }}/kibana.ini"
  when: ansible_ssh_host == 'RedHat'

- name: reread_and_update_supervisor_debian
  supervisorctl:
    state: present
    name: kibana
    config: "{{ supervisor_redhat_dir }}/kibana.ini"
  when: ansible_ssh_host == 'Debian'
