---

- name: stop zookeeper
  shell: "chdir={{ zookeeper_install_dir }}/bin . /etc/profile && ./zkServer.sh stop"
  ignore_errors: yes

- name: prepare for start
  wait_for: port=2181 state=stopped delay=2
  
- name: start zookeeper
  shell: "chdir={{ zookeeper_install_dir }}/bin . /etc/profile && ./zkServer.sh start"

- name: prepare for status
  wait_for: port=2181 state=started delay=2 connect_timeout=2

- name: check zookeeper status
  shell: "chdir={{ zookeeper_install_dir }}/bin . /etc/profile && ./zkServer.sh status"
  register: zk_status
- debug: msg="{{ zk_status.stdout }}"
