---

- name: register temp root password
  shell: "cat  {{ mysql_data_dir }}/mysqld.log | grep 'temporary password' | tail -1 | awk '{print $NF}'" 
  register: root_temp_password
- debug: msg="{{ root_temp_password }}"
- set_fact: temp_password="{{ root_temp_password.stdout }}"

- name: first reset root@localhost password to simple 123456
  shell: "mysql -uroot -p'{{ temp_password }}' -e 'set global validate_password_policy=0;' && mysql -uroot -p'{{ temp_password }}' -e 'set global validate_password_length=6;' && mysql -uroot -p'{{ temp_password }}' -e 'ALTER USER USER() IDENTIFIED BY '123456';' "
