---

- name: download prometheus
  when: not prometheus_store_name is exists
  delegate_to: localhost
  get_url:
    url: "{{ prometheus_download_url }}"
    validate_certs: no
    dest: "{{ soft_dir }}"

- name: scp soft
  synchronize:
    src: "{{ prometheus_store_name }}"
    dest: "{{ soft_dir }}"
    mode: push

- name: unarchive soft
  unarchive:
    src: "{{ prometheus_store_name }}"
    dest: "{{ prometheus_install_dir }}"

- name: link dir prometheus
  file:
    state: link
    path: "{{ prometheus_install_name }}"
    src: "{{ prometheus_install_name }}"
    dest: "{{ prometheus_link_dir }}"
    force: yes
    follow: yes

- name: create prometheus need dir
  file:
    state: directory
    path: "{{ item }}"
    force: yes
    follow: yes
  with_items:
      - "{{ prometheus_rule_conf_dir }}"
      - "{{ prometheus_node_conf_dir }}"
      - "{{ prometheus_data_dir }}"
      - "{{ prometheus_log_dir }}"

- name: config promethues rule config1
  synchronize: 
    src: files/linux_nodes.rules
    dest: "{{ prometheus_rule_conf_dir }}/"
    mode: push

- name: config promethues rule config2
  synchronize: 
    src: files/first.rules
    dest: "{{ prometheus_rule_conf_dir }}/"
