ETCD_DIR: "{{ INSTALL_DIR }}/{{ ETCD_INSTALL_NAME }}"
ETCD_CONF_DIR: "{{ ETCD_DIR }}/conf"
ETCD_CONF: "/etc/etcd/etcd.conf"
ETCD1: "10.0.0.5"
ETCD2: "10.0.0.6"
ETCD3: "10.0.0.7"
ETCD_DATA_DIR: "/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS: "http://{{ ansible_ssh_host }}:2380"
ETCD_LISTEN_CLIENT_URLS: "http://{{ ansible_ssh_host }}:2379,http://localhost:2379"
ETCD_NAME: "{{ etcd_name }}"
ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://{{ ansible_ssh_host }}:2380"
ETCD_ADVERTISE_CLIENT_URLS: "http://{{ ansible_ssh_host }}:2379,http://localhost:2379"
ETCD_INITIAL_CLUSTER: "etcd1=http://{{ ETCD1 }}:2380,etcd2=http://{{ ETCD2 }}:2380,etcd3=http://{{ ETCD3 }}:2380"
ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE: "new"
