---

- name: group add nginx user
  group: 
    name: www

- name: group add nginx user
  user:
    name: www
    group: www

- name: install epel repo 
  yum: 
    name: epel-release
    state: latest
    update_cache: yes

- name: install need pkgs
  yum:
    name: ['gcc','gcc-c++','automake','autoconf','cmake','openssl','openssl-devel','pcre-devel']
    state: latest

- name: download tengine 
  get_url:
    url: "{{ tengine_download_url }}"
    dest: "{{ soft_dir }}"
    validate_certs: no
  delegate_to: localhost
  when: not tengine_store_name is exists

- name: scp soft
  synchronize:
    src: "{{ tengine_store_name }}"
    dest: "{{ soft_dir }}"
    mode: push

- name: unarchive soft tengine
  unarchive:
    src: "{{ tengine_store_name }}"
    dest: "{{ soft_dir }}"
    copy: yes
    creates: "{{ soft_src_dir }}"

- name: config and make and make install
  shell: "chdir={{ soft_src_dir }} ./configure --prefix=/usr/local/tengine && make && make install"
