---
# defaults file for prometheus
soft_dir: /root/softs/
prometheus_version: 2.11.1
prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/v2.11.1/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
prometheus_store_name: "{{ soft_dir }}/{{ prometheus_version }}.linux-amd64.tar.gz" 
prometheus_install_dir: /opt/
prometheus_install_name: "{{ prometheus_install_dir }}/{{ prometheus_version,linux-amd64 }}"
promethues_link_dir: /opt/prometheus
