---

- hosts: all
  remote_user: root
  tasks:
    - name: add hostname to linux
      blockinfile:
        backup: yes
        path: /etc/hosts
        block: |
          172.17.14.159 temp_server02 ykb-temp-server002
          172.17.14.158 temp_server01  ykb-temp-server001      
          172.17.14.155 es-monitor
          172.17.14.145 ykb_new_test
          172.17.14.144 mongo-rabbitmq-git rabbitmq-mongo-git-apache-svn
          172.17.14.143 ykb-server-rukou  houtai_rukou    
          172.17.14.142 backend_web_php2_houtai  houtai_php_43
          172.17.14.141 backend_web_php1  houtai_php_218
