---

- hosts: localhost
  remote_user: root
  vars:
    users_info: [{"user":"zhouzhijia","password":"o3Rr(X5ta0Gbtjj[5I"},{"user":"wuqianang","password":"kpb4AG/m5lH}a90lmP"},{"user":"shiyiguo","password":"LXv57h.zr'Gxkw3Ou6"},{"user":"lishuming","password":"4dmip0LH<N9ir5Y:tp"},{"user":"zhoukun","password":"9iq4~iWMmLRpho54q*"}]
  tasks:
    - name: change password
      shell:  "echo {{ item.user }} {{ item.password }}"
      with_items:
        - users_info

