---
# defaults file for mongodb_cluster
mongodb_version: 4.0.11
mongodb_download_url: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-4.0.11.tgz
soft_dir: /root/softs/
soft_store_name: "{{ soft_dir }}mongodb-linux-x86_64-4.0.11.tgz"
install_dir: /usr/local/
install_link_dir: /usr/local/mongo
mongod_bin_dir: "{{ install_link_dir }}/bin"
mongod_bin: "{{ mongod_bin_dir }}/mongod"
install_dir_name: /usr/local/mongodb-linux-x86_64-4.0.11
mongo_config_dir: /data/mongo/conf
mongo_config_base_dir: /data/mongo/config
mongo_config_data_dir: "{{ mongo_config_base_dir}}/data"
mongo_config_log_dir: "{{ mongo_config_dir }}/log/"
mongo_config_log: "{{ mongo_config_log_dir }}/mongod.log"
mongo_config_pid: "{{ mongo_config_base_dir }}/mongod.pid"
mongo_config_conf: "{{ mongo_config_dir }}/config.conf"
mongo_config_start_cmd: "{{ mongod_bin_dir }}/mongod -f {{ mongo_config_conf }}"
mongo_config_port: 21004
user: mongo
group: mongo
mongo_data_dir: /data/mongo
shard1_base_dir: /data/mongo/shard1
shard2_base_dir: /data/mongo/shard2
shard3_base_dir: /data/mongo/shard3
shard1_data_dir: "{{ shard1_base_dir }}/data/"
shard2_data_dir: "{{ shard2_base_dir }}/data/"
shard3_data_dir: "{{ shard3_base_dir }}/data/"
shard1_log_dir: "{{ shard1_base_dir }}/log/"
shard2_log_dir: "{{ shard2_base_dir }}/log/"
shard3_log_dir: "{{ shard3_base_dir }}/log/"
shard1_log: "{{ shard1_log_dir }}mongod.log" 
shard1_pid: "{{ shard1_base_dir }}/mongod.pid"
shard2_pid: "{{ shard2_base_dir }}/mongod.pid"
shard3_pid: "{{ shard3_base_dir }}/mongod.pid"
shard1_port: 21001
shard1_config: "{{ mongo_config_dir }}/shard1.conf"
shard1_start_cmd: "{{ mongod_bin_dir }}/mongod -f {{ shard1_config }}"
shard2_log: "{{ shard2_log_dir }}mongod.log" 
shard2_port: 21002
shard2_config: "{{ mongo_config_dir }}/shard2.conf"
shard2_start_cmd: "{{ mongod_bin_dir }}/mongod -f {{ shard2_config }}"
shard3_log: "{{ shard3_log_dir }}mongod.log" 
shard3_port: 21003
shard3_config: "{{ mongo_config_dir }}/shard3.conf"
shard3_start_cmd: "{{ mongod_bin_dir }}/mongod -f {{ shard3_config }}"
mongod_data_dir: /data/mongo/config/data
mongod_log_dir: /data/mongo/config/log
mongod_log: "{{ mongod_log_dir }}/mongod.log"
mongod_pid: "/data/mongo/config/mongod.log"
mongod_port: 21004
mongos_base_dir: /data/mongo/mongos/
mongos_log_dir: "{{ mongos_base_dir }}/log"
mongos_config: "{{ mongo_config_dir }}/mongos.conf"
mongos_log: "{{ mongos_log_dir }}/mongos.log"
mongos_pid: "{{ mongos_base_dir }}/mongos.pid"
mongos_start_cmd: "{{ mongod_bin_dir }}/mongos -f {{ mongos_config }}"
mongos_port: 21000
mongod_log: "{{ mongo_config_dir }}/config/log"
mongo_auth_key: /data/mongo/conf/mongo.key
mongo_auth_key_cmd: openssl rand -base64 756 > /etc/mongodb/conf/mongo.key
supervisor_redhat_dir: /etc/supervisord.d/
supervisor_debian_dir: /etc/supervisor/conf.d/
mongodb_cluster_group_programs: mongo_config,mongos,shard1,shard2,shard3
